apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rice-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: rice-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: rice-db-secret
        property: DB_PASSWORD
