apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: rice-secretstore
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: hoangvm-rice-sa
