apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: rice-secretstore
  namespace: hoangvm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: hoangvm-rice-sa
